/// 핫큐·메모리 큐 개수(초안 기준).
public struct CueCounts: Hashable, Sendable {
    public var hot: Int
    public var memory: Int
    /// 메모리 큐 가운데 아직 고치지 않은 rekordbox 자동 큐(#145)
    public var autoMemory: Int

    public init(_ draft: CueDraft) {
        hot = draft.cues.filter { if case .hot = $0.kind { true } else { false } }.count
        memory = draft.cues.count - hot
        autoMemory = draft.cues.filter { $0.kind == .memory && $0.isAutoGenerated }.count
    }
}
