import Foundation

/// DJCrate 안에서 편집하는 큐. rekordbox에는 쓰지 않는다(검증된 반영 경로를 통해서만 나간다).
public struct EditableCue: Codable, Identifiable, Hashable, Sendable {
    public enum Kind: Codable, Hashable, Sendable {
        case memory
        /// 0…7 = A…H
        case hot(Int)

        public var slotLetter: String? {
            if case let .hot(slot) = self { return String(UnicodeScalar(UInt8(65 + slot))) }
            return nil
        }

        /// rekordbox `djmdCue.Kind` → 편집용. 매핑은 실측 분포 기반(0 → 메모리, 1,2,3 → A,B,C / 5…9 → D…H). 의미 미확인 Kind(4)는 nil
        public init?(rekordbox kind: Int) {
            switch kind {
            case 0: self = .memory
            case 1, 2, 3: self = .hot(kind - 1)
            case 5...9: self = .hot(kind - 2)
            default: return nil
            }
        }
    }

    /// 루프(rekordbox: 끝 지점 OutMsec, 활성 루프 ActiveLoop). 활성 루프는 곡을 불러오면 그 구간을 자동으로 반복한다.
    public struct Loop: Codable, Hashable, Sendable {
        /// 루프 끝(초, rekordbox 시간축)
        public var end: Double
        /// 활성 루프
        public var active: Bool
        /// 박 수(½박 = 0.5). nil = 박에 맞추지 않은 루프(rekordbox BeatLoopSize 0)
        public var beats: Double?

        public init(end: Double, active: Bool = false, beats: Double? = nil) {
            self.end = end; self.active = active; self.beats = beats
        }

        /// rekordbox `BeatLoopSize`(상위 16비트 = 분자, 하위 16비트 = 분모. 8박 = 8<<16|1, ½박 = 1<<16|2, 0 = 박 없음) → 박 수
        public static func beats(beatLoopSize value: Int) -> Double? {
            let numerator = value >> 16, denominator = value & 0xFFFF
            guard numerator > 0, denominator > 0 else { return nil }
            return Double(numerator) / Double(denominator)
        }

        /// 박 수 → rekordbox `BeatLoopSize`. 1박 이상은 정수, 1박 미만은 1/n만 쓴다. 나머지는 0(박 없음).
        public static func beatLoopSize(beats: Double?) -> Int {
            guard let beats, beats > 0 else { return 0 }
            if beats >= 1 {
                let whole = beats.rounded()
                return abs(beats - whole) < 0.001 && whole <= 0x7FFF ? Int(whole) << 16 | 1 : 0
            }
            let denominator = (1 / beats).rounded()
            return abs(1 / denominator - beats) < 0.0001 && denominator <= 0xFFFF ? 1 << 16 | Int(denominator) : 0
        }
    }

    public var id: UUID
    /// rekordbox `djmdCue.ID`. rekordbox에서 불러온 큐만 가진다.
    public var sourceID: String?
    public var kind: Kind
    public var time: Double
    public var name: String
    /// 루프면 끝 지점·활성 여부(옛 초안에는 없다)
    public var loop: Loop?

    /// - Parameter id: 새 큐의 ID(부르는 쪽이 준다. 핵심부는 ID를 스스로 만들지 않는다)
    public init(id: UUID, sourceID: String? = nil, kind: Kind, time: Double, name: String = "", loop: Loop? = nil) {
        self.id = id
        self.sourceID = sourceID
        self.kind = kind
        self.time = time
        self.name = name
        self.loop = loop
    }

    /// 루프 길이(초)
    public var loopLength: Double? { loop.map { $0.end - time } }

    /// rekordbox가 자동으로 넣은 큐(CUE(Auto)·1.1Bars). rekordbox처럼 메모리 큐로 보이고 똑같이 고친다(#145).
    public var isAutoGenerated: Bool { Cue.autoNames.contains(name.trimmingCharacters(in: .whitespaces)) }

    /// rekordbox 큐 → 편집용. 의미 미확인 Kind(4)는 편집 대상에서 뺀다(`Kind.init(rekordbox:)`). 자동 큐는 이름 그대로 둔다(이름이 곧 자동 표시).
    /// - Parameter id: 편집용 큐의 ID(부르는 쪽이 준다)
    public init?(_ cue: Cue, id: UUID) {
        guard let kind = Kind(rekordbox: cue.kind) else { return nil }
        self.init(id: id, sourceID: cue.id, kind: kind, time: Double(cue.inMsec) / 1000, name: cue.name,
                  loop: cue.isLoop ? Loop(end: Double(cue.outMsec) / 1000, active: cue.activeLoop > 0,
                                          beats: Loop.beats(beatLoopSize: cue.beatLoopSize)) : nil)
    }

    /// rekordbox 큐 가운데 편집할 수 있는 것만 편집용으로 바꾼다. ID는 편집할 수 있는 큐에만 `newID`로 받는다.
    public static func editable(_ cues: [Cue], newID: () -> UUID) -> [EditableCue] {
        cues.compactMap { cue in Kind(rekordbox: cue.kind) == nil ? nil : EditableCue(cue, id: newID()) }
    }
}

/// 곡 하나의 큐 초안. `base`는 편집을 시작할 때의 rekordbox 상태다.
public struct CueDraft: Codable, Equatable, Sendable {
    public var trackUUID: String
    public var base: [EditableCue]
    public var cues: [EditableCue]

    /// 빈 초안(지우기 표시, 편집본·옮긴 큐처럼 rekordbox 큐 없이 시작하는 초안)
    public init(trackUUID: String) {
        self.trackUUID = trackUUID
        base = []
        cues = []
    }

    /// rekordbox 큐로 시작하는 초안. 편집할 수 있는 큐마다 `newID`로 ID를 받는다(base·cues가 같은 ID).
    public init(trackUUID: String, rekordboxCues: [Cue], newID: () -> UUID) {
        self.trackUUID = trackUUID
        base = EditableCue.editable(rekordboxCues, newID: newID).sorted { $0.time < $1.time }
        cues = base
    }

    /// 자동 큐를 빼고 만든 초안(#145 이전 초안, 중복 합치기·곡 넣기처럼 base를 따로 정한 초안)에 rekordbox 자동 큐를 채운다.
    /// base에 없는 자동 큐만 base·cues 양쪽에 넣으므로 변경으로 치지 않고, 그 행은 쓰기에서 그대로 남는다.
    /// base에 있는데 cues에 없는 자동 큐는 사용자가 지운 것이라 되살리지 않는다. 채우는 큐의 ID는 `newID`로 받는다.
    public func includingAutoCues(from rekordboxCues: [Cue], newID: () -> UUID) -> CueDraft {
        let known = Set(base.compactMap(\.sourceID))
        let missing = EditableCue.editable(rekordboxCues.filter { $0.isAutoGenerated && !known.contains($0.id) }, newID: newID)
        guard !missing.isEmpty else { return self }
        var copy = self
        copy.base = (base + missing).sorted { $0.time < $1.time }
        copy.cues = (cues + missing).sorted { $0.time < $1.time }
        return copy
    }

    public enum Change: Hashable, Sendable {
        case added(EditableCue)
        case removed(EditableCue)
        case modified(from: EditableCue, to: EditableCue)
    }

    /// rekordbox 상태(`base`) 대비 변경. 시각은 1ms 미만 차이를 무시한다.
    public var changes: [Change] {
        let current = Dictionary(uniqueKeysWithValues: cues.map { ($0.id, $0) })
        var result: [Change] = []
        for old in base {
            guard let new = current[old.id] else { result.append(.removed(old)); continue }
            if old.kind != new.kind || abs(old.time - new.time) >= 0.001 || old.name != new.name
                || old.loop?.active != new.loop?.active || abs((old.loop?.end ?? -1) - (new.loop?.end ?? -1)) >= 0.001
                || old.loop?.beats != new.loop?.beats {
                result.append(.modified(from: old, to: new))
            }
        }
        let baseIDs = Set(base.map(\.id))
        result += cues.filter { !baseIDs.contains($0.id) }.map(Change.added)
        return result
    }

    public var hasChanges: Bool { !changes.isEmpty }

    /// 같은 슬롯의 핫큐는 하나만. 새로 놓는 쪽이 이긴다(기존 것은 제거).
    /// 자동 큐를 고치면(옮기기·루프·종류) 자동 이름을 비워 일반 큐로 만든다. 이름을 바꾼 것은 그 이름을 둔다(#145).
    public mutating func place(_ cue: EditableCue) {
        var cue = cue
        if let old = cues.first(where: { $0.id == cue.id }), old.isAutoGenerated, cue.name == old.name, cue != old { cue.name = "" }
        if case .hot = cue.kind { cues.removeAll { $0.kind == cue.kind && $0.id != cue.id } }
        if let index = cues.firstIndex(where: { $0.id == cue.id }) {
            cues[index] = cue
        } else {
            cues.append(cue)
        }
        cues.sort { $0.time < $1.time }
    }

    public mutating func remove(_ id: EditableCue.ID) {
        cues.removeAll { $0.id == id }
    }

    public mutating func revert() {
        cues = base
    }

    /// rekordbox로 내보내기 전 확인할 문제. 반영 경로 검증(V1) 때 기준을 확정한다.
    public func issues(duration: Double) -> [String] {
        var issues: [String] = []
        let slots = cues.compactMap(\.kind.slotLetter)
        if Set(slots).count != slots.count { issues.append(String(ui: "같은 핫큐 슬롯이 두 번 쓰였습니다")) }
        if cues.contains(where: { $0.time < 0 || $0.time > duration }) { issues.append(String(ui: "곡 길이를 벗어난 큐가 있습니다")) }
        return issues
    }
}

/// 초안은 곡 UUID별 JSON으로 Application Support에 둔다.
public extension CueDraft {
    /// 모든 큐(원본 포함)를 옮긴다. rekordbox 시간축 ↔ DJCrate 시간축 변환에 쓴다.
    func shifted(by seconds: Double) -> CueDraft {
        guard seconds != 0 else { return self }
        var copy = self
        copy.base = base.map { var cue = $0; cue.time += seconds; return cue }
        copy.cues = cues.map { var cue = $0; cue.time += seconds; return cue }
        return copy
    }
}
