import Foundation

/// 덱에서 큐를 고치는 규칙(초안만 바뀐다). rekordbox 제한과 CDJ 동작을 따른다.
public extension CueDraft {
    /// rekordbox는 곡당 메모리 큐를 10개까지 둔다(라이브러리 7천 곡 중 최대가 정확히 10개, 자동 큐 포함).
    static let memoryLimit = 10

    /// 메모리 큐 수. 자동 큐도 초안(목록)에 있으므로 목록에 보이는 수 그대로다.
    var memoryCount: Int { cues.filter { $0.kind == .memory }.count }

    /// 한도 알림. 자동 큐가 섞여 있으면 몇 개인지 함께 알린다(#145).
    var memoryLimitMessage: String {
        let auto = cues.filter { $0.kind == .memory && $0.isAutoGenerated }.count
        return auto > 0
            ? String(ui: "메모리 큐는 곡당 \(Self.memoryLimit)개까지입니다(rekordbox 자동 큐 \(auto)개 포함). 쓰지 않는 메모리 큐를 지운 뒤 찍으세요")
            : String(ui: "메모리 큐는 곡당 \(Self.memoryLimit)개까지입니다(rekordbox 제한). 쓰지 않는 메모리 큐를 지운 뒤 찍으세요")
    }

    func cue(_ id: EditableCue.ID?) -> EditableCue? {
        cues.first { $0.id == id }
    }

    func hotCue(slot: Int) -> EditableCue? {
        cues.first { $0.kind == .hot(slot) }
    }

    enum MemoryAddResult: Equatable {
        case added(EditableCue.ID)
        /// 같은 자리(±30ms)에 이미 있다 — 그 큐를 고른다
        case existing(EditableCue.ID)
        /// rekordbox 한도(10개)
        case limitReached
    }

    /// 메모리 큐(또는 `loop`이 있으면 메모리 루프)를 더한다. 새 큐의 ID는 더할 때만 `newID`로 받는다.
    mutating func addMemory(at time: Double, loop: EditableCue.Loop? = nil, newID: () -> UUID) -> MemoryAddResult {
        if let existing = cues.first(where: { $0.kind == .memory && abs($0.time - time) <= 0.03 && (loop == nil || $0.loop != nil) }) {
            return .existing(existing.id)
        }
        guard memoryCount < Self.memoryLimit else { return .limitReached }
        var cue = EditableCue(id: newID(), kind: .memory, time: time)
        cue.loop = loop
        place(cue)
        return .added(cue.id)
    }

    /// `times` 중 하나에서 ±30ms 안에 있는 메모리 큐 가운데 `time`에 가장 가까운 것(CDJ에서 불러온 자리의 DELETE).
    func memoryCue(near times: [Double], closestTo time: Double) -> EditableCue? {
        cues.filter { cue in cue.kind == .memory && times.contains { abs(cue.time - $0) <= 0.03 } }
            .min { abs($0.time - time) < abs($1.time - time) }
    }

    /// 옮긴다. 루프는 길이를 유지한다. 0.5ms 안이면 그대로 두고 false.
    @discardableResult
    mutating func move(_ id: EditableCue.ID, to time: Double) -> Bool {
        guard var cue = cue(id), abs(time - cue.time) >= 0.0005 else { return false }
        if let length = cue.loopLength { cue.loop?.end = time + length }
        cue.time = time
        place(cue)
        return true
    }

    /// 루프로 만든다(`end`가 nil이면 루프를 없앤다). 활성 여부는 이어받는다.
    mutating func setLoop(_ id: EditableCue.ID, end: Double?, beats: Double?) {
        guard var cue = cue(id) else { return }
        cue.loop = end.map { EditableCue.Loop(end: $0, active: cue.loop?.active ?? false, beats: beats) }
        place(cue)
    }

    /// 활성 루프(곡을 불러오면 자동 반복)를 켜고 끈다. 곡에 하나만 둔다.
    mutating func toggleActiveLoop(_ id: EditableCue.ID) {
        guard var cue = cue(id), cue.loop != nil else { return }
        let turningOn = !(cue.loop?.active ?? false)
        cue.loop?.active = turningOn
        if turningOn {
            for i in cues.indices where cues[i].id != cue.id && cues[i].loop?.active == true { cues[i].loop?.active = false }
        }
        place(cue)
    }
}
