import DJCStorage
import DJCDomain
import Foundation
import RekordboxFixtures
import RekordboxKit
import Testing

@Suite("읽기 JSON")
struct LibraryReadTests {
    @Test func 프리셋을_안_고르면_JSON에_규칙_집계가_없다() throws {
        let fixture = try fixture(), read = try reader(fixture)
        let report = try json("report", read.report(checkFiles: false))
        #expect(report["commentClasses"] == nil)
        #expect(report["prefixes"] == nil)
        #expect(report["usages"] == nil)
        #expect(throws: ReadFailure.self) { try read.search(query: "", filter: .offConvention) }
    }

    func fixture() throws -> RekordboxFixture { try readLibraryFixture() }

    func reader(_ fixture: RekordboxFixture, preset: CommentPreset = .none) throws -> LibraryRead {
        try LibraryRead(snapshot: fixture.database, home: fixture.root.appending(path: "home"), shareRoot: fixture.shareRoot, commentPreset: preset)
    }

    func json<T: Encodable>(_ command: String, _ result: T) throws -> [String: Any] {
        let encoded = try ReadJSON.encode(command: command, data: result)
        let envelope = try #require(JSONSerialization.jsonObject(with: encoded) as? [String: Any])
        #expect(Set(envelope.keys) == ["schemaVersion", "command", "data"])
        #expect(envelope["schemaVersion"] as? Int == 1)
        #expect(envelope["command"] as? String == command)
        return try #require(envelope["data"] as? [String: Any])
    }

    @Test func 검색_JSON과_교집합_필터() throws {
        let fixture = try fixture(), read = try reader(fixture, preset: .anisong)
        let data = try json("search", read.search(query: "ALPHA", bpm: 120...130, key: "8a", playlistID: "p1"))
        #expect(Set(data.keys) == ["tracks"])
        let tracks = try #require(data["tracks"] as? [[String: Any]])
        #expect(tracks.count == 1)
        #expect(tracks.first?["id"] as? String == "101")
        #expect(tracks.first?["bpm"] as? Double == 128)
        #expect(Set(try #require(tracks.first).keys) == ["id", "uuid", "title", "artist", "key", "bpm", "lengthSeconds", "path", "comment", "importedOn", "isStreaming"])
        #expect(try read.search(query: "").tracks.map(\.id) == ["101", "102"])
        #expect(try read.search(query: "없는 곡").tracks.isEmpty)
        #expect(try read.search(query: "", filter: .noBPM).tracks.map(\.id) == ["102"])
        #expect(try read.search(query: "", filter: .noCues).tracks.map(\.id) == ["102"])
        #expect(try read.search(query: "", filter: .emptyComment).tracks.map(\.id) == ["102"])
    }

    @Test func 곡_상세_JSON은_큐_그리드_게인_소속_초안을_담는다() throws {
        let fixture = try fixture(), read = try reader(fixture)
        let data = try json("track", read.track(id: "101"))
        #expect(Set(data.keys) == ["track", "cues", "grid", "gain", "playlists", "drafts"])
        let cues = try #require(data["cues"] as? [[String: Any]])
        #expect(cues.map { $0["id"] as? String } == ["memory", "loop"])
        #expect(cues.last?["hotCueSlot"] as? String == "A")
        #expect(cues.last?["isLoop"] as? Bool == true)
        #expect(cues.last?["outMsec"] as? Int == 3000)
        #expect(Set(try #require(cues.last).keys) == ["id", "kind", "hotCueSlot", "inMsec", "outMsec", "name", "isLoop", "activeLoop", "loopBeats", "isAutoGenerated", "color"])
        let grid = try #require(data["grid"] as? [String: Any])
        #expect(Set(grid.keys) == ["status", "beatCount", "segments", "tempoChanges"])
        #expect(grid["status"] as? String == "available")
        #expect(grid["beatCount"] as? Int == 16)
        #expect((grid["segments"] as? [Any])?.count == 1)
        let segment = try #require((grid["segments"] as? [[String: Any]])?.first)
        #expect(Set(segment.keys) == ["start", "bpm", "firstBeatNumber"])
        #expect((data["gain"] as? [String: Any])?["linear"] as? Double == 0.5)
        #expect(Set(try #require(data["gain"] as? [String: Any]).keys) == ["linear", "decibels", "peak"])
        #expect((data["playlists"] as? [[String: Any]])?.map { $0["id"] as? String } == ["p1"])
        #expect((data["drafts"] as? [String: Bool]) == ["cue": false, "grid": false, "gain": false, "tag": false, "artwork": false])
        let missing = try json("track", read.track(id: "102"))
        #expect(missing["gain"] == nil)
        #expect((missing["grid"] as? [String: Any])?["status"] as? String == "unavailable")
    }

    @Test func 재생목록_JSON은_트리와_곡순서_중복을_보존한다() throws {
        let fixture = try fixture(), read = try reader(fixture)
        let flat = try json("playlists", read.playlists(tree: false))
        #expect(Set(flat.keys) == ["playlists"])
        #expect((flat["playlists"] as? [Any])?.count == 3)
        let flatFirst = try #require((flat["playlists"] as? [[String: Any]])?.first)
        #expect(Set(flatFirst.keys) == ["id", "name", "parentID", "sequence", "isFolder", "trackCount"])
        let tree = try json("playlists", read.playlists(tree: true))
        let roots = try #require(tree["playlists"] as? [[String: Any]])
        #expect(roots.map { $0["id"] as? String } == ["f1", "p2"])
        #expect((roots.first?["children"] as? [[String: Any]])?.first?["id"] as? String == "p1")
        let list = try json("playlist", read.playlist(id: "p1"))
        #expect(Set(list.keys) == ["playlist", "tracks"])
        #expect((list["tracks"] as? [[String: Any]])?.map { $0["id"] as? String } == ["102", "101", "101"])
        #expect(try read.playlist(id: "f1").tracks.map(\.id) == ["102", "101"])
    }

    @Test func 초안_JSON은_게인과_고아초안도_담는다() throws {
        let fixture = try fixture()
        let home = fixture.root.appending(path: "home")
        try FileManager.default.createDirectory(at: home, withIntermediateDirectories: true)
        try Data(#"{"track-101":-3,"orphan":2}"#.utf8).write(to: home.appending(path: "gain-drafts.json"))
        let read = try reader(fixture)
        let data = try json("drafts", read.drafts())
        #expect(Set(data.keys) == ["drafts"])
        let drafts = try #require(data["drafts"] as? [[String: Any]])
        #expect(drafts.map { $0["trackUUID"] as? String } == ["orphan", "track-101"])
        #expect(drafts.first?["contentID"] == nil)
        #expect(drafts.last?["contentID"] as? String == "101")
        #expect(drafts.last?["kinds"] as? [String] == ["gain"])
        #expect(Set(try #require(drafts.last).keys) == ["trackUUID", "contentID", "title", "kinds"])
        #expect(try read.track(id: "101").drafts.gain)
    }

    @Test func 최신_스냅샷만_선택한다() throws {
        let fixture = try fixture()
        let directory = fixture.root.appending(path: "snapshots")
        let live = fixture.root.appending(path: "live/master.db")
        #expect(throws: (any Error).self) { try LibraryRead.resolve(database: nil, snapshots: directory, liveDatabase: live) }
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
        for name in ["master-2026-01-01T000000.db", "master-2026-01-02T000000.db"] {
            try FileManager.default.copyItem(at: fixture.database, to: directory.appending(path: name))
        }
        #expect(try LibraryRead.resolve(database: nil, snapshots: directory, liveDatabase: live).lastPathComponent == "master-2026-01-02T000000.db")
    }

    @Test func 라이브_DB와_심볼릭_링크와_하드_링크를_차단한다() throws {
        let fixture = try RekordboxFixture()
        let fm = FileManager.default
        let live = fixture.root.appending(path: "live/master.db")
        try fm.createDirectory(at: live.deletingLastPathComponent(), withIntermediateDirectories: true)
        try Data().write(to: live)
        let absolute = fixture.root.appending(path: "absolute.db")
        let relative = fixture.root.appending(path: "relative.db")
        let hard = fixture.root.appending(path: "hard.db")
        try fm.createSymbolicLink(at: absolute, withDestinationURL: live)
        try fm.createSymbolicLink(atPath: relative.path, withDestinationPath: "live/master.db")
        try fm.linkItem(at: live, to: hard)
        for candidate in [live, absolute, relative, hard] {
            #expect(throws: ReadFailure.self) { try LibraryRead.resolve(database: candidate, liveDatabase: live) }
        }
        let copy = fixture.root.appending(path: "copy.db")
        try fm.copyItem(at: live, to: copy)
        let copyAlias = fixture.root.appending(path: "copy-alias.db")
        try fm.createSymbolicLink(at: copyAlias, withDestinationURL: copy)
        #expect(try LibraryRead.resolve(database: copy, liveDatabase: live) == copy)
        #expect(try LibraryRead.resolve(database: copyAlias, liveDatabase: live) == copyAlias)
    }

    /// 임시 폴더는 `/tmp`·`/private/tmp` 두 표기로 불린다(#136). 표기가 달라도 라이브는 막고 사본은 연다.
    @Test(arguments: ["/tmp", "/private/tmp"])
    func 임시_폴더의_다른_표기로_줘도_라이브_DB를_막고_사본은_연다(_ parent: String) throws {
        let fixture = try RekordboxFixture(parent: URL(filePath: parent))
        let alias = { (url: URL) in
            URL(filePath: url.path.hasPrefix("/private/") ? String(url.path.dropFirst("/private".count)) : "/private" + url.path)
        }
        let fm = FileManager.default
        let live = fixture.root.appending(path: "live/master.db")
        try fm.createDirectory(at: live.deletingLastPathComponent(), withIntermediateDirectories: true)
        try Data().write(to: live)
        let link = fixture.root.appending(path: "link.db")
        try fm.createSymbolicLink(at: link, withDestinationURL: alias(live))
        for candidate in [alias(live), link] {
            #expect(throws: ReadFailure.self) { try LibraryRead.resolve(database: candidate, liveDatabase: live) }
        }
        let copy = fixture.root.appending(path: "copy.db")
        try fm.copyItem(at: live, to: copy)
        #expect(try LibraryRead.resolve(database: alias(copy), liveDatabase: live) == alias(copy))
    }

    @Test func 라이브_DB가_없어도_경로와_끊어진_링크를_차단한다() throws {
        let fixture = try RekordboxFixture()
        let fm = FileManager.default
        let live = fixture.root.appending(path: "missing/master.db")
        #expect(!fm.fileExists(atPath: live.path))
        let absolute = fixture.root.appending(path: "absolute.db")
        let relative = fixture.root.appending(path: "relative.db")
        try fm.createSymbolicLink(at: absolute, withDestinationURL: live)
        try fm.createSymbolicLink(atPath: relative.path, withDestinationPath: "missing/master.db")
        for candidate in [live, absolute, relative] {
            #expect(throws: ReadFailure.self) { try LibraryRead.resolve(database: candidate, liveDatabase: live) }
        }
        #expect(try LibraryRead.resolve(database: fixture.database, liveDatabase: live) == fixture.database)
    }

    @Test func 없는_ID는_JSON_오류다() throws {
        let fixture = try fixture(), read = try reader(fixture)
        #expect(throws: ReadFailure.self) { try read.track(id: "unknown") }
        #expect(throws: ReadFailure.self) { try read.playlist(id: "unknown") }
        #expect(throws: ReadFailure.self) { try read.search(query: "", playlistID: "unknown") }
        let encoded = try ReadJSON.error(command: "track", error: ReadFailure("not_found", "곡을 찾지 못했습니다. ID를 확인하세요"))
        let error = try #require(JSONSerialization.jsonObject(with: encoded) as? [String: Any])
        #expect(Set(error.keys) == ["schemaVersion", "command", "error"])
        #expect((error["error"] as? [String: String])?["code"] == "not_found")
    }

    @Test func 기존_읽기명령_JSON() throws {
        let fixture = try fixture(), read = try reader(fixture, preset: .anisong)
        let report = try json("report", read.report(checkFiles: false))
        #expect(Set(report.keys) == ["totalRows", "deletedRows", "liveTracks", "streamingTracks", "extensions", "commentClasses", "prefixes", "usages", "emptyByImportYear", "tracksWithCues", "tracksWithManualCues", "tracksWithOnlyAutoCues", "tracksWithoutCues", "hotCueSlots", "playedTracks", "emptyCommentPlayed"])
        #expect(report["liveTracks"] as? Int == 2 && report["deletedRows"] as? Int == 1)
        #expect(read.report(checkFiles: true).missingFiles == 2)
        let paths = try json("path", read.paths(query: "Alpha"))
        #expect(Set(paths.keys) == ["paths"])
        #expect(paths["paths"] as? [String] == ["/synthetic/alpha.mp3"])
        let parsed = try json("parse", LibraryRead.parse(comment: "TVA 시험 OP 1"))
        #expect(parsed["classification"] as? String == "convention")
        #expect(Set(parsed.keys) == ["classification", "parsed"])
        #expect((parsed["parsed"] as? [String: Any])?["workName"] as? String == "시험")
        #expect(Set(try #require(parsed["parsed"] as? [String: Any]).keys) == ["prefix", "workRef", "workName", "abbreviations", "usages", "episodes", "isCharacterSong", "isTVSize", "variants", "isFormerAffiliation", "boomboxVolumes"])
        #expect(LibraryRead.parse(comment: "").parsed == nil)
        let compat = try json("compat", LibraryRead.compatibility(snapshot: fixture.database, version: "7.2.18"))
        #expect(Set(compat.keys) == ["appVersion", "verifiedAppVersions", "databaseVersion", "localUpdateCount"])
        #expect(compat["databaseVersion"] as? String == "6000")
        #expect(compat["localUpdateCount"] as? Int == 1000)
    }

    @Test func 네_종류_초안은_DB_값과_파일을_바꾸지_않는다() throws {
        let fixture = try fixture()
        let library = try RekordboxLibrary.load(snapshot: fixture.database)
        let track = try #require(library.tracks.first(where: { $0.id == "101" }))
        let home = fixture.root.appending(path: "home")
        func put<T: Encodable>(_ value: T, at path: String) throws {
            let url = home.appending(path: path)
            try FileManager.default.createDirectory(at: url.deletingLastPathComponent(), withIntermediateDirectories: true)
            try JSONEncoder().encode(value).write(to: url)
        }
        var cue = CueDraft(trackUUID: track.uuid, rekordboxCues: library.cues(for: track))
        cue.cues.removeAll()
        try put(cue, at: "cue-drafts/track-101.json")
        try put(CueDraft(trackUUID: "track-102"), at: "cue-drafts/track-102.json")
        try put(GridDraft(trackUUID: track.uuid, base: [], segments: [.init(start: 1, bpm: 130, firstBeatNumber: 1)]), at: "grid-drafts/track-101.json")
        var tag = TagDraft(track: track)
        tag.fields.title = "초안 제목"
        try put(tag, at: "tag-drafts/track-101.json")
        try put([track.uuid: -3.0], at: "gain-drafts.json")
        let databaseBefore = try Data(contentsOf: fixture.database)
        let tagBefore = try Data(contentsOf: home.appending(path: "tag-drafts/track-101.json"))
        let read = try reader(fixture)
        let info = try read.track(id: track.id)
        #expect(info.drafts.kinds == ["cue", "grid", "gain", "tag"])
        #expect(info.track.title == "시험 Alpha" && info.cues.count == 2)
        #expect(read.drafts().drafts.count == 1)
        #expect(read.drafts().drafts.first?.kinds == ["cue", "grid", "gain", "tag"])
        #expect(try Data(contentsOf: fixture.database) == databaseBefore)
        #expect(try Data(contentsOf: home.appending(path: "tag-drafts/track-101.json")) == tagBefore)
    }

    @Test func 공유_필터는_스트리밍_변속_재생기록을_구분한다() throws {
        let fixture = try fixture()
        var streaming = TrackSpec(id: "104")
        streaming.title = "$A7:암호화된 제목"; streaming.folderPath = "spotify:synthetic"; streaming.bpm100 = 0
        try fixture.add(streaming)
        try fixture.execute("UPDATE djmdContent SET Commnt = '자유 코멘트' WHERE ID = '104'")
        try fixture.insert("djmdSongHistory", ["ID": .text("history-101"), "ContentID": .text("101")])
        var first = TrackSpec(id: "101")
        first.analysisDataPath = "/PIONEER/USBANLZ/test/ANLZ0000.DAT"
        let beats = AnlzBuilder.beats(bpm: 120, first: 0, count: 16) + AnlzBuilder.beats(bpm: 160, first: 8000, count: 16)
        try fixture.putAnalysis(for: first, dat: AnlzBuilder.dat(beats: beats), ext: nil)
        let read = try reader(fixture, preset: .anisong)
        let expected: [LibraryFilter: [String]] = [.emptyComment: ["102"], .offConvention: ["104"],
            .noCues: ["102", "104"], .played: ["101"], .streaming: ["104"], .noBPM: ["102"], .missingFile: ["101", "102"], .tempoChange: ["101"], .all: ["101", "102", "104"]]
        for filter in LibraryFilter.allCases {
            #expect(try read.search(query: "", filter: filter).tracks.map(\.id) == expected[filter])
        }
        #expect(try read.search(query: "암호화된 제목").tracks.isEmpty)
        #expect(try read.search(query: "합성 아티스트").tracks.map(\.id) == ["101"])
        #expect(try read.search(query: "Alpha", bpm: 129...130).tracks.isEmpty)
        #expect(try read.search(query: "Alpha", key: "8B").tracks.isEmpty)
        #expect(try read.search(query: "", playlistID: "f1").tracks.map(\.id) == ["101", "102"])
        #expect(Set(LibraryFilter.allCases.map(\.cliName)) == ["all", "empty-comment", "off-convention", "no-cues", "played", "streaming",
                                                               "no-bpm", "missing-file", "tempo-change"])
    }

    @Test func 파일_없음_필터는_음원을_찾지_못한_로컬_곡만_고른다() throws {
        let fixture = try fixture()
        var gone = TrackSpec(id: "105")
        gone.folderPath = fixture.audio.appending(path: "gone.mp3").path
        try fixture.add(gone)
        var external = TrackSpec(id: "106")
        external.folderPath = "/Volumes/DJC 시험 디스크 \(UUID().uuidString)/a.mp3"
        try fixture.add(external)
        var streaming = TrackSpec(id: "107")
        streaming.folderPath = "spotify:synthetic"
        try fixture.add(streaming)
        // 기본 사본의 101·102도 없는 합성 경로(/synthetic/…)다. 스트리밍 곡(104·107)은 세지 않는다.
        #expect(try reader(fixture).search(query: "", filter: .missingFile).tracks.map(\.id) == ["101", "102", "105", "106"])
    }

    @Test func 빈_코멘트는_연도와_스트리밍을_제한하지_않는다() throws {
        let fixture = try fixture()
        var streaming = TrackSpec(id: "104")
        streaming.folderPath = "spotify:synthetic"
        try fixture.add(streaming)
        try fixture.execute("UPDATE djmdContent SET StockDate = '2024-01-01' WHERE ID = '102'")
        try fixture.execute("UPDATE djmdContent SET StockDate = '2027-01-01' WHERE ID = '104'")
        #expect(try reader(fixture, preset: .anisong).search(query: "", filter: .emptyComment).tracks.map(\.id) == ["102", "104"])
    }
}
