import DJCDomain
import Foundation
import RekordboxFixtures
@testable import RekordboxKit
import Testing

@Suite("rekordbox 라이브러리 읽기")
struct RekordboxLibraryTests {
    /// 곡 2개(하나는 삭제 행) + 아티스트·앨범·장르·키·재생 목록·재생 이력·오토게인
    func makeLibrary() throws -> (RekordboxFixture, TrackSpec, TrackSpec) {
        let fixture = try RekordboxFixture()
        for (table, id, name) in [("djmdArtist", "ar1", "아티스트"), ("djmdArtist", "ar2", "작곡가"), ("djmdArtist", "ar3", "앨범 아티스트"),
                                  ("djmdGenre", "g1", "Anime")] {
            try fixture.insert(table, ["ID": .text(id), "Name": .text(name)])
        }
        try fixture.insert("djmdAlbum", ["ID": .text("al1"), "Name": .text("앨범"), "AlbumArtistID": .text("ar3")])
        try fixture.insert("djmdKey", ["ID": .text("k1"), "ScaleName": .text("8B")])

        var live = TrackSpec(id: "101")
        live.title = "살아 있는 곡"
        live.bpm100 = 17450
        live.cues = [.autoCue(at: 1000), CueSpec(id: "c2", kind: 5, inMsec: 20_000)]
        live.gain = RekordboxAutoGain.halves(0.5)
        try fixture.add(live)
        try fixture.execute("""
            UPDATE djmdContent SET ArtistID = 'ar1', ComposerID = 'ar2', AlbumID = 'al1', GenreID = 'g1', KeyID = 'k1',
                Commnt = 'TVA 작품 OP 1', ReleaseYear = 2024, TrackNo = 3, ImagePath = '/PIONEER/Artwork/1.jpg' WHERE ID = '101'
            """)
        var deleted = TrackSpec(id: "102")
        deleted.title = "지운 곡"
        try fixture.add(deleted)
        try fixture.execute("UPDATE djmdContent SET rb_local_deleted = 1 WHERE ID = '102'")
        // 삭제된 큐 행은 읽지 않는다
        try fixture.execute("UPDATE djmdCue SET rb_local_deleted = 1 WHERE ID = 'c2'")

        for (id, name, parent, attribute, seq) in [("f1", "폴더", "root", 1, 1), ("p1", "셋 A", "f1", 0, 2), ("p2", "셋 B", "f1", 0, 1),
                                                   ("p3", "맨 위", "root", 0, 0)] {
            try fixture.insert("djmdPlaylist", ["ID": .text(id), "Name": .text(name), "ParentID": .text(parent),
                                                "Attribute": .int(attribute), "Seq": .int(seq)])
        }
        for (id, playlist, content, no) in [("s1", "p1", "101", 2), ("s2", "p1", "102", 1), ("s3", "p2", "101", 1), ("s4", "p2", "101", 2)] {
            try fixture.insert("djmdSongPlaylist", ["ID": .text(id), "PlaylistID": .text(playlist), "ContentID": .text(content),
                                                    "TrackNo": .int(no)])
        }
        for n in 0..<3 { try fixture.insert("djmdSongHistory", ["ID": .text("h\(n)"), "ContentID": .text("101")]) }
        return (fixture, live, deleted)
    }

    @Test func 곡_정보는_연결된_표에서_채운다() throws {
        let (fixture, live, _) = try makeLibrary()
        let library = try RekordboxLibrary.load(snapshot: fixture.database)
        #expect(library.allTracks.count == 2 && library.tracks.count == 1)
        let track = try #require(library.tracks.first)
        #expect(track.id == live.id && track.uuid == live.uuid && track.title == "살아 있는 곡")
        #expect(track.artist == "아티스트" && track.composer == "작곡가" && track.album == "앨범" && track.albumArtist == "앨범 아티스트")
        #expect(track.genre == "Anime" && track.key == "8B" && track.bpm == 174.5)
        #expect(track.comment == "TVA 작품 OP 1" && track.releaseYear == 2024 && track.trackNumber == 3)
        #expect(track.importedOn == "2026-01-01" && !track.isDeleted)
    }

    @Test func 큐는_삭제_행을_빼고_재생_이력은_센다() throws {
        let (fixture, live, _) = try makeLibrary()
        let library = try RekordboxLibrary.load(snapshot: fixture.database)
        let track = try #require(library.tracks.first)
        let cues = library.cues(for: track)
        #expect(cues.count == 1 && cues[0].isAutoGenerated)
        #expect(library.playCounts[live.id] == 3)
        let gain = try #require(library.autoGains[live.id])
        #expect(abs(gain.gain - 0.5) < 1e-6 && abs(gain.gainDB - 20 * log10(0.5)) < 1e-6)
    }

    @Test func 재생_목록은_순서대로_트리로() throws {
        let (fixture, live, deleted) = try makeLibrary()
        let library = try RekordboxLibrary.load(snapshot: fixture.database)
        let tree = PlaylistNode.tree(library.playlists)
        #expect(tree.map(\.name) == ["맨 위", "폴더"])
        let folder = try #require(tree.last)
        #expect(folder.isFolder && folder.children?.map(\.name) == ["셋 B", "셋 A"])
        // 셋 A: TrackNo 순서(지운 곡 102가 1번), 셋 B: 같은 곡 두 번은 한 번만
        #expect(folder.find("p1")?.trackIDs == [deleted.id, live.id])
        #expect(folder.find("p2")?.trackIDs == [live.id])
        #expect(folder.trackIDs == [live.id, deleted.id], "폴더는 하위 곡을 순서대로 모으고 중복을 뺀다")
    }

    @Test func 일반_표에_들어온_목록은_보조_XML_없이_이름과_곡_순서를_보존한다() throws {
        // #100: 일반 표에 저장된 목록의 읽기만 확인한다. iTunes 동기화 캐시 형식을 가정하지 않는다.
        let (fixture, live, _) = try makeLibrary()
        try fixture.add(TrackSpec(id: "103"))
        for (id, name, parent, folder, seq) in [
            ("import-folder", "가져온 폴더", "root", true, 3),
            ("import-a", "같은 이름", "import-folder", false, 2),
            ("import-b", "같은 이름", "import-folder", false, 1),
        ] {
            try fixture.insert("djmdPlaylist", ["ID": .text(id), "Name": .text(name), "ParentID": .text(parent),
                                                "Attribute": .int(folder ? 1 : 0), "Seq": .int(seq)])
        }
        for (id, content, no, deleted) in [("entry-a", "103", 9, 0), ("entry-z", live.id, 2, 0),
                                           ("entry-b", "103", 5, 1), ("entry-c", live.id, 12, 0)] {
            try fixture.insert("djmdSongPlaylist", ["ID": .text(id), "PlaylistID": .text("import-a"),
                                                    "ContentID": .text(content), "TrackNo": .int(no), "rb_local_deleted": .int(deleted)])
        }
        let snapshot = try LibrarySnapshot.take(from: fixture.database, into: fixture.root.appending(path: "snapshots"), force: true)
        let before = try Data(contentsOf: snapshot)
        let library = try RekordboxLibrary.load(snapshot: snapshot)
        #expect(Set(library.playlists.map(\.id)) == ["f1", "p1", "p2", "p3", "import-folder", "import-a", "import-b"])
        let imported = try #require(library.playlists.first { $0.id == "import-a" })
        #expect(imported.trackIDs == [live.id, "103", live.id] && imported.trackNumbers == [2, 9, 12])
        let tree = PlaylistNode.tree(library.playlists)
        let folder = try #require(tree.first { $0.id == "import-folder" })
        #expect(folder.children?.map(\.id) == ["import-b", "import-a"])
        #expect(folder.children?.map(\.name) == ["같은 이름", "같은 이름"], "이름으로 합치거나 거르지 않는다")
        #expect(folder.children?.first?.trackIDs.isEmpty == true, "빈 목록도 남긴다")
        #expect(folder.trackIDs == [live.id, "103"])
        let outline = PlaylistOutlineNode.tree(PlaylistLayout(rekordbox: library.playlists))
        #expect(outline.map(\.id) == tree.map(\.id))
        #expect(outline.first { $0.id == "import-folder" }?.children?.map(\.id) == ["import-b", "import-a"])
        #expect(try Data(contentsOf: snapshot) == before, "읽기는 스냅샷을 고치지 않는다")
    }

    @Test func 현황은_삭제_행을_빼고_센다() throws {
        let (fixture, _, _) = try makeLibrary()
        let report = LibraryReport(library: try RekordboxLibrary.load(snapshot: fixture.database))
        #expect(report.totalRows == 2 && report.deletedRows == 1 && report.liveTracks == 1)
        #expect(report.playedTracks == 1 && report.tracksWithOnlyAutoCues == 1)
        #expect(!report.render().isEmpty)
    }

    @Test func 스냅샷은_사본을_뜨고_최근_것만_남긴다() throws {
        let (fixture, _, _) = try makeLibrary()
        let folder = fixture.root.appending(path: "snapshots")
        var taken: [URL] = []
        for n in 0..<5 {
            taken.append(try LibrarySnapshot.take(from: fixture.database, into: folder, force: true,
                                                  now: Date(timeIntervalSince1970: 1_790_000_000 + Double(n))))
        }
        let files = try FileManager.default.contentsOfDirectory(atPath: folder.path).filter { $0.hasSuffix(".db") }
        #expect(files.count == 3, "최근 3개만 남긴다")
        #expect(try LibrarySnapshot.latest(in: folder).lastPathComponent == taken.last?.lastPathComponent)
        #expect(try RekordboxLibrary.load(snapshot: taken.last!).allTracks.count == 2)
    }

    /// USB 동기화는 선택 파일의 Timestamp를 masterPlaylists6.xml에서 옮긴다. 라이브 폴더의 XML을 읽지 않도록 스냅샷 옆에 사본을 둔다.
    @Test func 스냅샷은_재생_목록_XML도_옆에_복사하고_정리할_때_함께_지운다() throws {
        let (fixture, _, _) = try makeLibrary()
        let xml = fixture.database.deletingLastPathComponent().appending(path: "masterPlaylists6.xml")
        try Data("<PLAYLISTS>합성</PLAYLISTS>".utf8).write(to: xml)
        let folder = fixture.root.appending(path: "snapshots")
        var taken: [URL] = []
        for n in 0..<4 {
            taken.append(try LibrarySnapshot.take(from: fixture.database, into: folder, force: true,
                                                  now: Date(timeIntervalSince1970: 1_790_000_000 + Double(n))))
        }
        let copy = LibrarySnapshot.masterPlaylistsURL(of: taken.last!)
        #expect(try Data(contentsOf: copy) == Data("<PLAYLISTS>합성</PLAYLISTS>".utf8))
        #expect(!FileManager.default.fileExists(atPath: LibrarySnapshot.masterPlaylistsURL(of: taken[0]).path), "지운 스냅샷의 XML도 지운다")
        // 사본에서 다시 뜨면 사본 옆 XML을 옮긴다(라이브 XML이 바뀌어도 같은 때의 XML).
        try Data("<PLAYLISTS>바뀜</PLAYLISTS>".utf8).write(to: xml)
        let again = try LibrarySnapshot.take(from: taken.last!, into: fixture.root.appending(path: "again"), force: true)
        #expect(try Data(contentsOf: LibrarySnapshot.masterPlaylistsURL(of: again)) == Data("<PLAYLISTS>합성</PLAYLISTS>".utf8))
    }

    @Test func 스냅샷_뒤에_rekordbox가_라이브러리를_바꿨는지_안다() throws {
        let (fixture, _, _) = try makeLibrary()
        let folder = fixture.root.appending(path: "snapshots")
        let taken = Date(timeIntervalSince1970: 1_790_000_000)
        let snapshot = try LibrarySnapshot.take(from: fixture.database, into: folder, force: true, now: taken)
        #expect(LibrarySnapshot.takenAt(snapshot) == taken, "파일 이름의 시각(UTC, 초 단위)")
        #expect(LibrarySnapshot.takenAt(URL(filePath: "/x/other.db")) == nil)
        let fm = FileManager.default
        try fm.setAttributes([.modificationDate: taken.addingTimeInterval(-60)], ofItemAtPath: fixture.database.path)
        #expect(!LibrarySnapshot.changed(since: snapshot, source: fixture.database))
        // rekordbox가 켜져 있으면 변경은 WAL에만 있다
        let wal = URL(filePath: fixture.database.path + "-wal")
        try Data([1]).write(to: wal)
        try fm.setAttributes([.modificationDate: taken.addingTimeInterval(30)], ofItemAtPath: wal.path)
        #expect(LibrarySnapshot.changed(since: snapshot, source: fixture.database))
        try fm.removeItem(at: wal)
        try fm.setAttributes([.modificationDate: taken.addingTimeInterval(5)], ofItemAtPath: fixture.database.path)
        #expect(LibrarySnapshot.changed(since: snapshot, source: fixture.database))
    }
}
