import DJCApplication
import DJCDomain
import Foundation
import Synchronization
import Testing

/// 곡 목록의 초안 색인. 초안 파일 없이 가짜 저장소로 시험한다.
@Suite("곡 목록 초안 색인")
struct WatchDraftsTests {
    /// 가짜 초안 저장소: 메모리 초안과 부른 읽기, 그때 메인 스레드였는지 남긴다.
    final class Fake: Sendable {
        struct State {
            var cues: [String: CueDraft] = [:]
            var tags: [String: TagDraft] = [:]
            var grids: Set<String> = []
            var gains: Set<String> = []
            var artwork: [String: ArtworkDraft] = [:]
            var unsaved = UnsavedDrafts()
            var failedTags: Set<String> = []
            var stamps: [String: Date] = [:]
            var revision: UInt64 = 0
            var damaged: [DamagedDraftFile] = []
            var calls: [String] = []
            var onMain: [String] = []
        }
        let state = Mutex(State())

        func record(_ name: String) {
            state.withLock {
                $0.calls.append(name)
                if Thread.isMainThread { $0.onMain.append(name) }
            }
        }
        var calls: [String] { state.withLock { $0.calls } }
        var mainCalls: [String] { state.withLock { $0.onMain } }

        /// 색인이 읽는 것만 기록하는 초안 저장소(나머지는 메모리 구현)
        var repository: DraftStore {
            var store = MemoryDrafts().store
            store.flush = { self.record("flush") }
            store.saveRevision = { self.state.withLock { $0.revision } }
            store.fileStamps = { self.record("stamps"); return self.state.withLock { $0.stamps } }
            store.preserveDamaged = { self.record("damaged"); return self.state.withLock { $0.damaged } }
            store.cueDraftUUIDs = { self.record("cueUUIDs"); return Set(self.state.withLock { $0.cues.keys }) }
            store.cueDraft = { uuid in self.record("cue"); return self.state.withLock { $0.cues[uuid] } }
            store.tagDraftUUIDs = { self.record("tagUUIDs"); return Set(self.state.withLock { $0.tags.keys }) }
            store.tagDraft = { uuid in self.record("tag"); return self.state.withLock { $0.tags[uuid] } }
            store.gridDraftUUIDs = { self.record("grids"); return self.state.withLock { $0.grids } }
            store.gainDraftUUIDs = { self.record("gains"); return self.state.withLock { $0.gains } }
            store.artworkDrafts = { self.record("artwork"); return self.state.withLock { $0.artwork } }
            store.playlistDraft = { self.record("playlist"); return PlaylistDraft() }
            store.unsaved = { self.state.withLock { $0.unsaved } }
            store.failedTagSaves = { self.state.withLock { $0.failedTags } }
            return store
        }
    }

    static let auto = Cue(id: "auto", contentID: "1", kind: 0, inMsec: 350, name: "1.1Bars", colorTableIndex: 0, color: 255)

    static func cueDraft(_ uuid: String, hot slot: Int? = 0) -> CueDraft {
        var draft = CueDraft(trackUUID: uuid)
        if let slot { draft.place(EditableCue(kind: .hot(slot), time: 10)) }
        return draft
    }

    static func tagDraft(_ uuid: String, comment: String) -> TagDraft {
        var draft = TagDraft(trackUUID: uuid, base: TagFields())
        draft.fields.comment = comment
        return draft
    }

    @Test func 라이브러리를_읽을_때_초안을_모으고_옛_큐_초안에_자동_큐를_채운다() {
        let fake = Fake()
        fake.state.withLock {
            $0.cues = ["a": Self.cueDraft("a", hot: nil), "b": Self.cueDraft("b")]
            $0.tags = ["a": Self.tagDraft("a", comment: "코멘트")]
            $0.grids = ["c"]
            $0.gains = ["d"]
        }
        let loaded = WatchDrafts(drafts: fake.repository).load(autoCues: ["a": [Self.auto]])
        #expect(loaded.cueDraftUUIDs == ["a", "b"] && loaded.gridDraftUUIDs == ["c"] && loaded.gainDraftUUIDs == ["d"])
        #expect(loaded.cueDrafts["a"]?.cues.first?.isAutoGenerated == true && loaded.cueDrafts["a"]?.hasChanges == false)
        #expect(loaded.tagDrafts["a"]?.fields.comment == "코멘트")
    }

    @Test func 파일이_그대로이고_저장_대기_입력이_없으면_내용을_읽지_않는다() async {
        let fake = Fake()
        let stamp = Date(timeIntervalSince1970: 1)
        fake.state.withLock { $0.stamps = ["/home/cue-drafts/a.json": stamp]; $0.cues = ["a": Self.cueDraft("a")] }
        let unchanged = await WatchDrafts(drafts: fake.repository).refresh(since: ["/home/cue-drafts/a.json": stamp], preservingDamaged: true)
        #expect(unchanged.contents == nil)
        #expect(fake.calls == ["flush", "stamps"], "저장을 끝낸 뒤 파일 시각만 본다")
    }

    @MainActor
    @Test func 바뀐_파일은_메인_스레드_밖에서_다시_읽고_저장_대기_입력을_얹는다() async {
        let fake = Fake()
        let pending = Self.cueDraft("b", hot: 2)
        fake.state.withLock {
            $0.stamps = ["/home/cue-drafts/a.json": Date(timeIntervalSince1970: 2)]
            $0.cues = ["a": Self.cueDraft("a"), "b": Self.cueDraft("b")]
            $0.tags = ["a": Self.tagDraft("a", comment: "바깥"), "b": TagDraft(trackUUID: "b", base: TagFields())]
            $0.unsaved = UnsavedDrafts(cues: ["b": pending])
            $0.revision = 7
            $0.damaged = [DamagedDraftFile(name: "cue-drafts/x.json", preserved: URL(filePath: "/home/damaged-drafts/x.json"), trackUUID: "x")]
        }
        // 메인 액터에서 불러도 읽기는 메인 밖에서 한다
        let refresh = await WatchDrafts(drafts: fake.repository).refresh(since: [:], preservingDamaged: true)
        let contents = refresh.contents
        #expect(contents != nil)
        #expect(refresh.saveRevision == 7)
        #expect(contents?.cueDrafts["b"] == pending, "저장 대기 입력이 디스크보다 최신이다")
        #expect(contents?.tagDrafts.keys.sorted() == ["a"], "고친 것이 없는 태그 초안은 뺀다")
        #expect(contents?.moved.map(\.trackUUID) == ["x"])
        #expect(fake.calls.first == "flush" && fake.mainCalls.isEmpty, "메인 스레드에서 읽음: \(fake.mainCalls)")

        // 앱 데이터 폴더를 정하지 않은 저장소는 손상 파일을 옮기지 않는다
        let quiet = Fake()
        _ = await WatchDrafts(drafts: quiet.repository).refresh(since: nil, preservingDamaged: false)
        #expect(!quiet.calls.contains("damaged"))
    }

    @Test func 목록에_보일_큐_초안은_자동_큐를_채우고_고친_것만_남긴다() {
        let drafts = ["a": Self.cueDraft("a", hot: nil), "b": Self.cueDraft("b")]
        let visible = WatchDrafts.visibleCueDrafts(drafts) { $0 == "a" ? [Self.auto] : [] }
        #expect(visible.keys.sorted() == ["b"])
    }

    @Test func 바깥_태그는_저장에_실패한_곡의_메모리_입력을_지킨다() {
        let memory = ["a": Self.tagDraft("a", comment: "메모리"), "b": Self.tagDraft("b", comment: "그대로")]
        let disk = ["a": Self.tagDraft("a", comment: "디스크"), "b": Self.tagDraft("b", comment: "그대로")]
        #expect(WatchDrafts.externalTags(disk: disk, memory: memory, failed: ["a"]) == nil, "실패한 곡만 다르면 그대로")
        #expect(WatchDrafts.externalTags(disk: disk, memory: memory, failed: [])?["a"]?.fields.comment == "디스크")
        #expect(WatchDrafts.externalTags(disk: [:], memory: memory, failed: [])?.isEmpty == true, "바깥에서 지운 초안")
    }

    @Test func 다시_읽은_태그는_편집_중이면_메모리를_쓰고_동기화면_base를_옮긴다() {
        let loaded = ["a": Self.tagDraft("a", comment: "디스크")]
        let memory = ["a": Self.tagDraft("a", comment: "읽는 중 편집")]
        #expect(WatchDrafts.reloadedTags(loaded: loaded, memory: memory, editedDuringRead: false, failed: [], synchronizing: false,
                                        currentFields: { _ in nil }).tags == loaded)
        #expect(WatchDrafts.reloadedTags(loaded: loaded, memory: memory, editedDuringRead: true, failed: [], synchronizing: false,
                                        currentFields: { _ in nil }).tags == memory)
        #expect(WatchDrafts.reloadedTags(loaded: [:], memory: memory, editedDuringRead: false, failed: ["a"], synchronizing: false,
                                        currentFields: { _ in nil }).tags == memory)

        // 동기화: 바뀌지 않은 칸은 base만 옮기고, 같은 칸이 rekordbox에서도 바뀌면 충돌로 남긴다. 라이브러리에 없는 곡은 건너뛴다
        var title = TagDraft(trackUUID: "t", base: TagFields())
        title.fields.title = "초안 제목"
        var current = TagFields()
        current.comment = "rekordbox에서 고침"
        let tags = ["t": title, "c": Self.tagDraft("c", comment: "초안"), "x": Self.tagDraft("x", comment: "없는 곡")]
        let reload = WatchDrafts.reloadedTags(loaded: tags, memory: [:], editedDuringRead: false, failed: [], synchronizing: true) { uuid in
            switch uuid {
            case "t": current
            case "c": { var fields = TagFields(); fields.comment = "rekordbox 코멘트"; return fields }()
            default: nil
            }
        }
        #expect(reload.tags["t"]?.base == current && reload.tags["t"]?.fields.title == "초안 제목")
        #expect(reload.rebased.map(\.trackUUID) == ["t"] && reload.conflicts == 1)
        #expect(reload.tags["c"] == tags["c"] && reload.tags["x"] == tags["x"])
    }

    @Test func 저장_대기_입력이_초안_표시를_바꾼다() {
        var cue: Set<String> = ["a"], grid: Set<String> = ["g"], gain: Set<String> = ["x"]
        let gains: [String: Double?] = ["x": nil, "y": -2]
        let unsaved = UnsavedDrafts(cues: ["a": Self.cueDraft("a", hot: nil), "b": Self.cueDraft("b")],
                                    grids: ["g": GridDraft(trackUUID: "g", base: [], segments: [])],
                                    gains: gains)
        let counted = unsaved.overlay(cue: &cue, grid: &grid, gain: &gain)
        #expect(cue == ["b"] && grid.isEmpty && gain == ["y"])
        #expect(counted.map(\.trackUUID) == ["a", "b"])
    }

    @Test func 읽기_순번은_늦은_결과를_가른다() {
        var reads = LibraryReadSequence()
        let first = reads.beginSnapshot()
        #expect(reads.isCurrent(first.generation) && reads.isCurrentRequest(first.request))
        let load = reads.beginLoad()
        #expect(!reads.isCurrent(first.generation) && !reads.isCurrentRequest(first.request) && reads.isCurrent(load))
        reads.invalidate()
        #expect(!reads.isCurrent(load) && reads.request == 2, "버리기는 요청 순번을 올리지 않는다")
    }
}
