@testable import DJCDomain
import Foundation
import Testing

/// 덱 규칙(루프 길이·끝, 메모리 큐 추가·한도·지우기, 활성 루프, 루프 유지 이동, 게인, 다음 큐까지 박)
@Suite("루프 규칙")
struct LoopRulesTests {
    /// 120 BPM, 0.5초부터 박
    let grid = BeatGrid(beats: (0..<200).map { BeatGrid.Beat(number: $0 % 4 + 1, bpm: 120, time: 0.5 + Double($0) * 0.5) })

    @Test func 길이_사다리와_표시() {
        #expect(LoopRules.sizes == [0.25, 0.5, 1, 2, 4, 8, 16, 32])
        #expect(LoopRules.resized(4, direction: -1) == 2 && LoopRules.resized(4, direction: 1) == 8)
        #expect(LoopRules.resized(0.25, direction: -1) == nil && LoopRules.resized(32, direction: 1) == nil)
        #expect(LoopRules.resized(3, direction: 1) == 8, "사다리 밖 값(3박)은 그 위 칸(4) 기준")
        #expect(LoopRules.text(0.25) == "¼" && LoopRules.text(0.5) == "½" && LoopRules.text(8) == "8")
    }

    @Test func 끝은_그리드_박에_맞추고_1박_미만은_BPM으로_나눈다() {
        #expect(LoopRules.end(from: 10.5, beats: 4, grid: grid, fallbackBPM: nil, duration: 100) == 12.5)
        #expect(abs((LoopRules.end(from: 10.5, beats: 0.5, grid: grid, fallbackBPM: nil, duration: 100) ?? 0) - 10.75) < 1e-9)
        // 그리드가 없으면 알려 준 BPM, 그것도 없으면 120
        #expect(abs((LoopRules.end(from: 10, beats: 8, grid: nil, fallbackBPM: 150, duration: 100) ?? 0) - 13.2) < 1e-9)
        #expect(abs((LoopRules.end(from: 10, beats: 2, grid: nil, fallbackBPM: nil, duration: 100) ?? 0) - 11) < 1e-9)
    }

    @Test func 곡_끝을_넘는_루프는_없다() {
        // 그리드가 있으면 마지막 박에서 멈춘다(99초 + 8박 → 100초 박), 없으면 BPM으로 재서 넘으면 nil
        #expect(LoopRules.end(from: 99, beats: 8, grid: grid, fallbackBPM: nil, duration: 100) == 100)
        #expect(LoopRules.end(from: 99, beats: 8, grid: nil, fallbackBPM: 120, duration: 100) == nil)
    }

    @Test func 루프_박_수() {
        var cue = EditableCue(kind: .hot(0), time: 10.5)
        cue.loop = EditableCue.Loop(end: 14.5, beats: nil)
        #expect(LoopRules.beats(of: cue, grid: grid, bpm: nil) == 8)
        #expect(LoopRules.beats(of: cue, grid: nil, bpm: 120) == 8)
        #expect(LoopRules.beats(of: EditableCue(kind: .memory, time: 1), grid: grid, bpm: nil) == nil)
    }
}

@Suite("큐 편집 규칙")
struct CueEditingRulesTests {
    func draft(_ cues: [EditableCue] = []) -> CueDraft {
        var draft = CueDraft(trackUUID: "t")
        for cue in cues { draft.place(cue) }
        return draft
    }

    @Test func 메모리_큐_추가는_같은_자리면_고르고_한도면_막는다() {
        var d = draft([EditableCue(kind: .memory, time: 10)])
        guard case .existing = d.addMemory(at: 10.02) else { Issue.record("±30ms면 새로 만들지 않는다"); return }
        guard case .added = d.addMemory(at: 20) else { Issue.record("추가"); return }
        #expect(d.cues.filter { $0.kind == .memory }.count == 2)
        // 핫큐는 세지 않고 메모리 큐 10개면 더 못 만든다
        d = draft((1...10).map { EditableCue(kind: .memory, time: Double($0) * 10) } + [EditableCue(kind: .hot(0), time: 5)])
        guard case .limitReached = d.addMemory(at: 150) else { Issue.record("한도"); return }
        #expect(d.memoryCount == 10 && CueDraft.memoryLimit == 10)
    }

    /// #145: 한도는 목록에 보이는 메모리 큐 수 그대로다(자동 큐도 목록에 있다). 알림은 자동 큐가 몇 개 섞였는지 함께 말한다.
    @Test func 한도는_보이는_메모리_큐로_세고_알림은_자동_큐_수를_알린다() {
        let auto = [(0.3, "CUE(Auto)"), (7.8, "1.1Bars"), (67.8, "1.1Bars"), (127.8, "1.1Bars")].map {
            Cue(id: "\($0.0)", contentID: "c", kind: 0, inMsec: Int($0.0 * 1000), name: $0.1, colorTableIndex: 0, color: 255)
        }
        var d = CueDraft(trackUUID: "t", rekordboxCues: auto)
        for time in [5.0, 15, 25, 70, 95] { _ = d.addMemory(at: time) }
        guard case .added = d.addMemory(at: 105) else { Issue.record("자동 4 + 6 = 10까지는 찍힌다"); return }
        guard case .limitReached = d.addMemory(at: 115) else { Issue.record("11번째는 막는다"); return }
        #expect(d.memoryLimitMessage
            == "메모리 큐는 곡당 10개까지입니다(rekordbox 자동 큐 4개 포함). 쓰지 않는 메모리 큐를 지운 뒤 찍으세요")
        // 자동 큐 하나를 지우면 하나 더 찍을 수 있다.
        d.remove(d.cues.first(where: \.isAutoGenerated)!.id)
        guard case .added = d.addMemory(at: 115) else { Issue.record("자동 큐를 지우면 자리가 난다"); return }
        let manual = draft((1...10).map { EditableCue(kind: .memory, time: Double($0) * 10) })
        #expect(manual.memoryLimitMessage == "메모리 큐는 곡당 10개까지입니다(rekordbox 제한). 쓰지 않는 메모리 큐를 지운 뒤 찍으세요")
    }

    @Test func 메모리_루프로_추가() {
        var d = draft()
        guard case let .added(id) = d.addMemory(at: 30, loop: EditableCue.Loop(end: 32, beats: 4)) else {
            Issue.record("추가"); return
        }
        #expect(d.cues.first { $0.id == id }?.loop?.end == 32)
    }

    @Test func 지울_메모리_큐는_가장_가까운_것() {
        let d = draft([EditableCue(kind: .memory, time: 10), EditableCue(kind: .memory, time: 10.025), EditableCue(kind: .hot(0), time: 10.01)])
        #expect(d.memoryCue(near: [10.02], closestTo: 10.02)?.time == 10.025)
        #expect(d.memoryCue(near: [11], closestTo: 11) == nil)
    }

    @Test func 활성_루프는_하나만() {
        var a = EditableCue(kind: .hot(0), time: 10), b = EditableCue(kind: .hot(1), time: 20)
        a.loop = EditableCue.Loop(end: 12, active: true)
        b.loop = EditableCue.Loop(end: 22)
        var d = draft([a, b])
        d.toggleActiveLoop(b.id)
        #expect(d.cue(b.id)?.loop?.active == true && d.cue(a.id)?.loop?.active == false)
        d.toggleActiveLoop(b.id)
        #expect(d.cue(b.id)?.loop?.active == false)
    }

    @Test func 루프를_옮기면_길이를_지킨다() {
        var loop = EditableCue(kind: .hot(0), time: 10)
        loop.loop = EditableCue.Loop(end: 14, beats: 8)
        var d = draft([loop])
        let moved = d.move(loop.id, to: 20)
        #expect(moved)
        #expect(d.cue(loop.id)?.time == 20 && d.cue(loop.id)?.loop?.end == 24)
        let tiny = d.move(loop.id, to: 20.0001)
        #expect(!tiny, "0.5ms 안이면 그대로")
    }

    @Test func 박_수로_루프를_걸고_푼다() {
        let cue = EditableCue(kind: .hot(0), time: 10)
        var d = draft([cue])
        d.setLoop(cue.id, end: 12, beats: 4)
        #expect(d.cue(cue.id)?.loop == EditableCue.Loop(end: 12, active: false, beats: 4))
        d.setLoop(cue.id, end: nil, beats: nil)
        #expect(d.cue(cue.id)?.loop == nil)
    }
}

@Suite("게인 계산")
struct GainPolicyTests {
    @Test func 쓰는_값의_우선순위는_초안_rekordbox_측정() {
        var policy = GainPolicy()
        #expect(policy.autoGainDB(rekordbox: -3, measured: -2, draft: -1) == -1)
        #expect(policy.autoGainDB(rekordbox: -3, measured: -2, draft: nil) == -3)
        #expect(policy.autoGainDB(rekordbox: nil, measured: -2, draft: nil) == -2)
        policy.useRekordbox = false
        #expect(policy.autoGainDB(rekordbox: -3, measured: -2, draft: nil) == -2)
        policy.enabled = false
        #expect(policy.autoGainDB(rekordbox: -3, measured: -2, draft: -1) == 0)
    }

    @Test func 트림을_더하고_범위를_지킨다() {
        var policy = GainPolicy()
        policy.trim = 2
        #expect(policy.applied(autoGainDB: -3) == -1)
        policy.trim = 12
        #expect(policy.applied(autoGainDB: 20) == 24)
    }

    @Test func rekordbox_값이_잰_음량과_1_5dB_넘게_다르면_이상하다() {
        // rekordbox는 −10 LUFS에 맞춘다: 음량 −6 LUFS 곡이면 −4dB가 맞다
        #expect(GainPolicy.mismatch(rekordbox: -4, integratedLoudness: -6) == 0)
        #expect(GainPolicy.mismatch(rekordbox: -1, integratedLoudness: -6) == 3)
        #expect(GainPolicy.isSuspicious(mismatch: 1.6) && !GainPolicy.isSuspicious(mismatch: 1.4))
    }

    @Test func 곡_게인_초안은_rekordbox와_같으면_지운다() {
        #expect(GainPolicy.draft(for: -3.02, rekordbox: -3) == nil)
        #expect(GainPolicy.draft(for: -1, rekordbox: -3) == -1)
        #expect(GainPolicy.draft(for: 40, rekordbox: -3) == 24)
    }
}

@Suite("다음 메모리 큐까지")
struct CueCountdownTests {
    let grid = BeatGrid(beats: (0..<400).map { BeatGrid.Beat(number: $0 % 4 + 1, bpm: 120, time: Double($0) * 0.5) })

    @Test func 박_수로_세고_64박_넘으면_마디() {
        let cues = [EditableCue(kind: .memory, time: 20), EditableCue(kind: .hot(0), time: 12), EditableCue(kind: .memory, time: 100)]
        #expect(CueCountdown.text(to: cues, from: 12.1, grid: grid) == "−16 Beats")
        #expect(CueCountdown.text(to: cues, from: 20.1, grid: grid) == "−40.4 Bars")
        #expect(CueCountdown.text(to: cues, from: 100.1, grid: grid) == nil)
        #expect(CueCountdown.text(to: cues, from: 12, grid: nil) == "−8.0s")
    }

    /// #144: 마디.박은 박 번호처럼 .4 → .1로 줄고, .1 다음에 마디가 하나 준다(남은 B박 = −((B−1)/4+1).((B−1)%4+1)).
    @Test func 마디_표시의_박은_4에서_1로_센다() {
        let cues = [EditableCue(kind: .memory, time: 100)]  // 200번째 박
        let texts = [76, 75, 74, 73, 72, 66, 65, 64].map { beats in
            CueCountdown.text(to: cues, from: Double(200 - beats) * 0.5 + 0.1, grid: grid)
        }
        #expect(texts == ["−19.4 Bars", "−19.3 Bars", "−19.2 Bars", "−19.1 Bars", "−18.4 Bars", "−17.2 Bars", "−17.1 Bars", "−64 Beats"])
    }

    @Test func 남은_양은_박_또는_초로_센다() {
        let cues = [EditableCue(kind: .memory, time: 20), EditableCue(kind: .memory, time: 100)]
        #expect(CueCountdown.remaining(to: cues, from: 12.1, grid: grid) == .beats(16))
        #expect(CueCountdown.remaining(to: cues, from: 20.1, grid: grid) == .beats(160))
        #expect(CueCountdown.remaining(to: cues, from: 12, grid: nil) == .seconds(8))
        #expect(CueCountdown.remaining(to: cues, from: 100.1, grid: grid) == nil)
        #expect(CueCountdown.remaining(to: [EditableCue(kind: .hot(0), time: 20)], from: 12, grid: grid) == nil, "핫큐는 세지 않는다")
    }
}
